changelog:
  categories:
    - title: "?? Bug Fixes"
      labels:
        - fix
      keywords:
        - fix
    - title: "?? New Features"
      labels:
        - feat
      keywords:
        - feat
    - title: "?? Documentation"
      labels:
        - docs
      keywords:
        - docs